LOAD DATA LOCAL INFILE '/var/www/html/projet1/alimenter_la_base_de_teste/vente.csv'
INTO TABLE vente
FIELDS TERMINATED BY ','
LINES TERMINATED BY '\r\n'
IGNORE 1 LINES
(CODART,NUMFOU,DELLIV,QTE1,PRIX1,QTE2,PRIX2,QTE3,PRIX3);